# Site Settings
baseurl: ""
url : "https://skalimoi.github.io"

# Blog Settings
theme_settings :
  title : Stranded Lands
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Stranded Lands
    description : I like worldbuilding, maps, and many other things. 
    experience :
      - start : 
        end : 
        experience : 
    skills : 
      - skill : 
        value : 
        
  # Icons
  icons :
    email: skalimoi@protonmail.com
    linkedin:  # Full URL 
    github: 
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: pmmdkmgk
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :
  comments : true

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
