#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'A worldbuilding and map blog.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # About

  In this website I post my creative works, aside from random thoughts and tutorials on the Blog section.

  # Supporting me

  In case you want to support me, you can buy me a coffee: [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/J3J62VTSA)

contact: >
  # Contact

  You can contact me via [Telegram](https://t.me/skalimoi), [Twitter (Spanish only)](https://twitter.com/skalimoi) and [e-mail](mailto:skalimoi@protonmail.com) for any questions, comments, and commission inquiries.

#-------------------------------
# Work Section

projects:
- {name: 'Atlas Map: Hellion', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Technical Map: The Northern Front', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
